version: "3.3"

services:
  rabbit:
    image: heidiks/rabbitmq-delayed-message-exchange:latest
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=password
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq # Persist RabbitMQ data
    networks:
      - rabbitmq_network

volumes:
  rabbitmq_data:
    driver: local

networks:
  rabbitmq_network:
    driver: bridge
